Description: Creates Data Lake Imovel

#Todos os recursos da Aws
Resources:
#  VPC - Rede interna da Aws
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.1.0.0/16"
      EnableDnsHostnames: true
      EnableDnsSupport: true
# Dentro de cada região a Aws disponibiliza uma quantidade de Subnet ( Ec2 - Maquina para controlar Rede ) ( Distribur IP para os serviços )
  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub "${AWS::Region}a"
      CidrBlock: 10.1.1.0/24
      VpcId: !Ref Vpc

  Subnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref Subnet1

  Subnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub "${AWS::Region}b"
      CidrBlock: 10.1.2.0/24
      VpcId: !Ref Vpc

  Subnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref Subnet2

  Subnet3:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub "${AWS::Region}c"
      CidrBlock: 10.1.3.0/24
      VpcId: !Ref Vpc

  Subnet3RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref Subnet3
# Liberar acesso externo
  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref Vpc
      InternetGatewayId: !Ref InternetGateway

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc

  IgwVPCRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref RouteTable


# Encriptar os dados
#  DataLakeEncryptionKey:
#    Type: AWS::KMS::Key
#    Properties:
#      Description: Data lake encryption key
#      Enabled: true
#      EnableKeyRotation: true
#      KeyUsage: ENCRYPT_DECRYPT
#      KeyPolicy:
#        Version: '2012-10-17'
#        Id: key-default-1
#        Statement:
#          - Sid: Enable IAM User Permissions
#            Effect: Allow
#            Principal:
#              AWS: !Ref AWS::AccountId
#            Action: kms:*
#            Resource: '*'


Outputs: # Saída das dependências ( Depois de criar um recurso exporta a referencia )
  VpcId:
    Value: !Ref Vpc
    Export:
      Name: networking-VpcId

  Subnet1:
    Value: !Ref Subnet1
    Export:
      Name: networking-Subnet1

  Subnet2:
    Value: !Ref Subnet2
    Export:
      Name: networking-Subnet2

  Subnet3:
    Value: !Ref Subnet3
    Export:
      Name: networking-Subnet3