Description: RDS

#Todos os recursos da Aws
Resources:

  ImoveisProductionSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: production-common/imoveis-production-sg
      GroupName: imoveis-production-sg
      SecurityGroupIngress:
        - IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 5432
          ToPort: 5432
      VpcId:
        Fn::ImportValue: networking-VpcId
    Metadata:
      'aws:cdk:path': production-common/imoveis-production-sg/Resource'

  SGBaseIngress:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
        GroupId: !Ref ImoveisProductionSecurityGroup
        IpProtocol: tcp
        FromPort: 5432
        ToPort: 5432
        SourceSecurityGroupId: !GetAtt ImoveisProductionSecurityGroup.GroupId

  ImoveisProductionrdsParameterGroup:
    Type: 'AWS::RDS::DBParameterGroup'
    Properties:
      Description: Parameter group to allow CDC from RDS using DMS.
      Family: postgres12
      Parameters:
        rds.logical_replication: '1'
        wal_sender_timeout: '0'
    Metadata:
      'aws:cdk:path': production-common/imoveis-production-rds-parameter-group/Resource'

  ImoveisProductionRDSSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Description:
        'Fn::Join':
          - ''
          - - 'Generated by the CDK for stack: '
            - Ref: 'AWS::StackName'
      GenerateSecretString:
        ExcludeCharacters: ' %+~`#$&*()|[]{}:;<>?!''/@"\'
        GenerateStringKey: password
        PasswordLength: 30
        SecretStringTemplate: '{"username":"postgres"}'
    Metadata:
      'aws:cdk:path': production-common/imoveis-production-rds/Secret/Resource'

  ImoveisProductionRDS:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceClass: db.t2.micro
      AllocatedStorage: '100'
      CopyTagsToSnapshot: true
      DBInstanceIdentifier: rds-production-imoveis-db
      DBName: imoveis
      DBParameterGroupName:
        Ref: ImoveisProductionrdsParameterGroup
      DBSubnetGroupName: !ImportValue networking-RDSProductionSubnet
      Engine: postgres
      EngineVersion: '12.4'
      MasterUsername:
        'Fn::Join':
          - ''
          - - '{{resolve:secretsmanager:'
            - Ref: ImoveisProductionRDSSecret
            - ':SecretString:username::}}'
      MasterUserPassword:
        'Fn::Join':
            - ''
            - - '{{resolve:secretsmanager:'
              - Ref: ImoveisProductionRDSSecret
              - ':SecretString:password::}}'
      Port: '5432'
      PubliclyAccessible: true
      StorageType: gp2
      VPCSecurityGroups:
        - 'Fn::GetAtt':
          - ImoveisProductionSecurityGroup
          - GroupId
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      'aws:cdk:path': production-common/imoveis-production-rds/Resource'

  ImoveisProductionRDSSecretAttachment:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Properties:
      SecretId: !Ref ImoveisProductionRDSSecret
      TargetId: !Ref ImoveisProductionRDS
      TargetType: 'AWS::RDS::DBInstance'
    Metadata:
      'aws:cdk:path': production-common/imoveis-production-rds/Secret/Attachment/Resource'

  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.80.0,@aws-cdk/assets=1.71.0,@aws-cdk/aws-applicationautoscaling=1.71.0,@aws-cdk/aws-athena=1.71.0,@aws-cdk/aws-autoscaling-common=1.71.0,@aws-cdk/aws-cloudwatch=1.71.0,@aws-cdk/aws-codeguruprofiler=1.71.0,@aws-cdk/aws-dms=1.71.0,@aws-cdk/aws-ec2=1.71.0,@aws-cdk/aws-efs=1.71.0,@aws-cdk/aws-emr=1.71.0,@aws-cdk/aws-events=1.71.0,@aws-cdk/aws-glue=1.71.0,@aws-cdk/aws-iam=1.71.0,@aws-cdk/aws-kinesisfirehose=1.71.0,@aws-cdk/aws-kms=1.71.0,@aws-cdk/aws-lambda=1.71.0,@aws-cdk/aws-logs=1.71.0,@aws-cdk/aws-rds=1.71.0,@aws-cdk/aws-redshift=1.71.0,@aws-cdk/aws-s3=1.71.0,@aws-cdk/aws-s3-assets=1.71.0,@aws-cdk/aws-sam=1.71.0,@aws-cdk/aws-secretsmanager=1.71.0,@aws-cdk/aws-sqs=1.71.0,@aws-cdk/aws-ssm=1.71.0,@aws-cdk/cloud-assembly-schema=1.71.0,@aws-cdk/core=1.71.0,@aws-cdk/cx-api=1.71.0,@aws-cdk/region-info=1.71.0,jsii-runtime=Python/3.8.5
    Metadata:
      aws:cdk:path: production-data-lake-raw-ingestion/CDKMetadata/Default
Conditions:
  CDKMetadataAvailable:
    'Fn::Or':
      - 'Fn::Or':
        - 'Fn::Equals':
            - Ref: 'AWS::Region'
            - ap-east-1
        - 'Fn::Equals':
            - Ref: 'AWS::Region'
            - ap-northeast-1
        - 'Fn::Equals':
            - Ref: 'AWS::Region'
            - ap-northeast-2
        - 'Fn::Equals':
            - Ref: 'AWS::Region'
            - ap-south-1
        - 'Fn::Equals':
            - Ref: 'AWS::Region'
            - ap-southeast-1
        - 'Fn::Equals':
            - Ref: 'AWS::Region'
            - ap-southeast-2
        - 'Fn::Equals':
            - Ref: 'AWS::Region'
            - ca-central-1
        - 'Fn::Equals':
            - Ref: 'AWS::Region'
            - cn-north-1
        - 'Fn::Equals':
            - Ref: 'AWS::Region'
            - cn-northwest-1
        - 'Fn::Equals':
            - Ref: 'AWS::Region'
            - eu-central-1
      - 'Fn::Or':
        - 'Fn::Equals':
            - Ref: 'AWS::Region'
            - eu-north-1
        - 'Fn::Equals':
            - Ref: 'AWS::Region'
            - eu-west-1
        - 'Fn::Equals':
            - Ref: 'AWS::Region'
            - eu-west-2
        - 'Fn::Equals':
            - Ref: 'AWS::Region'
            - eu-west-3
        - 'Fn::Equals':
            - Ref: 'AWS::Region'
            - me-south-1
        - 'Fn::Equals':
            - Ref: 'AWS::Region'
            - sa-east-1
        - 'Fn::Equals':
            - Ref: 'AWS::Region'
            - us-east-1
        - 'Fn::Equals':
            - Ref: 'AWS::Region'
            - us-east-2
        - 'Fn::Equals':
            - Ref: 'AWS::Region'
            - us-west-1
        - 'Fn::Equals':
            - Ref: 'AWS::Region'
            - us-west-2

Outputs:
  ImoveisProductionRDSSecretAttachment:
    Value:
      Ref: ImoveisProductionRDSSecretAttachment
    Export:
      Name: >-
        production-common:ImoveisProductionRDSSecretAttachment
  ImoveisProductionRDS:
    Value:
      'Fn::GetAtt':
          - ImoveisProductionRDS
          - Endpoint.Address
    Export:
      Name: >-
        production-common:ImoveisProductionRDS