Description: Criando migração de dados de postgresql para s3

Resources:

  IamDataLakeDMSRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: dms.amazonaws.com
        Version: '2012-10-17'
      Description: Role to allow DMS to save data to data lake raw

  IamDataLakeDMSPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
        - Action:
            - s3:PutObjectTagging
            - s3:DeleteObject
            - s3:ListBucket
            - s3:PutObject
          Effect: Allow
          Resource:
            - arn:aws:s3:::*
        Version: '2012-10-17'
      PolicyName: iam-production-data-lake-raw-dms-policy
      Roles:
      - Ref: IamDataLakeDMSRole
    Metadata:
      aws:cdk:path: production-data-lake-raw-ingestion/iam-production-data-lake-raw-dms-role/iam-production-data-lake-raw-dms-policy/Resource

  DMSProductionImoveisRDSendpoint:
    Type: AWS::DMS::Endpoint
    Properties:
      EndpointType: source
      EngineName: postgres
      DatabaseName:
        Fn::Join:
        - ''
        - - "{{resolve:secretsmanager:"
          - Fn::ImportValue: production-common:ImoveisProductionRDSSecretAttachment
          - ":SecretString:dbname}}"
      EndpointIdentifier: dms-source-production-imoveis-rds-endpoint
      ExtraConnectionAttributes: captureDDLs=Y
      Password:
        Fn::Join:
        - ''
        - - "{{resolve:secretsmanager:"
          - Fn::ImportValue: production-common:ImoveisProductionRDSSecretAttachment
          - ":SecretString:password}}"
      Port: 5432
      ServerName:
        Fn::ImportValue: production-common:ImoveisProductionRDS
      Username:
        Fn::Join:
        - ''
        - - "{{resolve:secretsmanager:"
          - Fn::ImportValue: production-common:ImoveisProductionRDSSecretAttachment
          - ":SecretString:username}}"
    Metadata:
      aws:cdk:path: production-data-lake-raw-ingestion/dms-production-imoveis-rds-endpoint

  DMSProductionImoveisS3Endpoint:
    Type: AWS::DMS::Endpoint
    Properties:
      EndpointType: target
      EngineName: s3
      EndpointIdentifier: dms-target-production-imoveis-s3-endpoint
      ExtraConnectionAttributes: DataFormat=parquet;maxFileSize=131072;timestampColumnName=extracted_at;includeOpForFullLoad=true;cdcInsertsAndUpdates=true
      S3Settings:
        BucketFolder: netimoveis
        BucketName: !ImportValue data-lake-DataLakeImovelRawBucketName
        CompressionType: gzip
        CsvDelimiter: ","
        CsvRowDelimiter: "\n"
        ServiceAccessRoleArn:
          Fn::GetAtt:
          - IamDataLakeDMSRole
          - Arn
    Metadata:
      aws:cdk:path: production-data-lake-raw-ingestion/dms-production-imoveis-s3-endpoint

  DMSProductionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: production-data-lake-raw-ingestion/dms-production-sg
      GroupName: dms-production-sg
      SecurityGroupEgress:
      - CidrIp: 0.0.0.0/0
        Description: Allow all outbound traffic by default
        IpProtocol: "-1"
      VpcId:
        Fn::ImportValue: networking-VpcId
    Metadata:
      aws:cdk:path: production-data-lake-raw-ingestion/dms-production-sg/Resource

  DMSReplicationInstanceProduction:
    Type: AWS::DMS::ReplicationInstance
    Properties:
      ReplicationInstanceClass: dms.t2.small
      AllocatedStorage: 100
      EngineVersion: 3.3.3
      PubliclyAccessible: false
      ReplicationInstanceIdentifier: dms-production-replication-instance
      ReplicationSubnetGroupIdentifier: dms-production-replication-subnet
      VpcSecurityGroupIds:
      - Fn::GetAtt:
        - DMSProductionSecurityGroup
        - GroupId
    Metadata:
      aws:cdk:path: production-data-lake-raw-ingestion/dms-replication-instance-production

  DMSTaskImoveisRDS:
    Type: AWS::DMS::ReplicationTask
    Properties:
      MigrationType: full-load-and-cdc
      ReplicationInstanceArn:
        Ref: DMSReplicationInstanceProduction
      SourceEndpointArn:
        Ref: DMSProductionImoveisRDSendpoint
      TableMappings: '{"rules": [{"rule-type": "selection", "rule-id": "1", "rule-name":
        "1", "object-locator": {"schema-name": "%", "table-name": "%"}, "rule-action":
        "include", "filters": []}]}'
      TargetEndpointArn:
        Ref: DMSProductionImoveisS3Endpoint
      ReplicationTaskIdentifier: production-dms-task-imoveis-rds
    Metadata:
      aws:cdk:path: production-data-lake-raw-ingestion/production-dms-task-imoveis-rds

  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.80.0,@aws-cdk/assets=1.71.0,@aws-cdk/aws-applicationautoscaling=1.71.0,@aws-cdk/aws-athena=1.71.0,@aws-cdk/aws-autoscaling-common=1.71.0,@aws-cdk/aws-cloudwatch=1.71.0,@aws-cdk/aws-codeguruprofiler=1.71.0,@aws-cdk/aws-dms=1.71.0,@aws-cdk/aws-ec2=1.71.0,@aws-cdk/aws-efs=1.71.0,@aws-cdk/aws-emr=1.71.0,@aws-cdk/aws-events=1.71.0,@aws-cdk/aws-glue=1.71.0,@aws-cdk/aws-iam=1.71.0,@aws-cdk/aws-kinesisfirehose=1.71.0,@aws-cdk/aws-kms=1.71.0,@aws-cdk/aws-lambda=1.71.0,@aws-cdk/aws-logs=1.71.0,@aws-cdk/aws-rds=1.71.0,@aws-cdk/aws-redshift=1.71.0,@aws-cdk/aws-s3=1.71.0,@aws-cdk/aws-s3-assets=1.71.0,@aws-cdk/aws-sam=1.71.0,@aws-cdk/aws-secretsmanager=1.71.0,@aws-cdk/aws-sqs=1.71.0,@aws-cdk/aws-ssm=1.71.0,@aws-cdk/cloud-assembly-schema=1.71.0,@aws-cdk/core=1.71.0,@aws-cdk/cx-api=1.71.0,@aws-cdk/region-info=1.71.0,jsii-runtime=Python/3.8.5
    Metadata:
      aws:cdk:path: production-data-lake-raw-ingestion/CDKMetadata/Default
    Condition: CDKMetadataAvailable

Conditions:
  CDKMetadataAvailable:
    Fn::Or:
    - Fn::Or:
      - Fn::Equals:
        - Ref: AWS::Region
        - ap-east-1
      - Fn::Equals:
        - Ref: AWS::Region
        - ap-northeast-1
      - Fn::Equals:
        - Ref: AWS::Region
        - ap-northeast-2
      - Fn::Equals:
        - Ref: AWS::Region
        - ap-south-1
      - Fn::Equals:
        - Ref: AWS::Region
        - ap-southeast-1
      - Fn::Equals:
        - Ref: AWS::Region
        - ap-southeast-2
      - Fn::Equals:
        - Ref: AWS::Region
        - ca-central-1
      - Fn::Equals:
        - Ref: AWS::Region
        - cn-north-1
      - Fn::Equals:
        - Ref: AWS::Region
        - cn-northwest-1
      - Fn::Equals:
        - Ref: AWS::Region
        - eu-central-1
    - Fn::Or:
      - Fn::Equals:
        - Ref: AWS::Region
        - eu-north-1
      - Fn::Equals:
        - Ref: AWS::Region
        - eu-west-1
      - Fn::Equals:
        - Ref: AWS::Region
        - eu-west-2
      - Fn::Equals:
        - Ref: AWS::Region
        - eu-west-3
      - Fn::Equals:
        - Ref: AWS::Region
        - me-south-1
      - Fn::Equals:
        - Ref: AWS::Region
        - sa-east-1
      - Fn::Equals:
        - Ref: AWS::Region
        - us-east-1
      - Fn::Equals:
        - Ref: AWS::Region
        - us-east-2
      - Fn::Equals:
        - Ref: AWS::Region
        - us-west-1
      - Fn::Equals:
        - Ref: AWS::Region
        - us-west-2
      